"""add agent_thread

Revision ID: 0751335fd491
Revises: 72392e84a097
Create Date: 2026-08-03 21:18:49.756239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0751335fd491'
down_revision: Union[str, Sequence[str], None] = '72392e84a097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Tabel mungkin sudah dibuat oleh init_db() (Base.metadata.create_all)
    # saat server start pertama kali — skip jika sudah ada (idempotent).
    conn = op.get_bind()
    exists = conn.execute(
        sa.text("SELECT to_regclass('public.agent_thread')")
    ).scalar()
    if exists is not None:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cv_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_id'], ['user_cv.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index(op.f('ix_agent_thread_id'), 'agent_thread', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_thread_id'), table_name='agent_thread')
    op.drop_table('agent_thread')
    # ### end Alembic commands ###
