"""add public_sharing fields to user_cv

Revision ID: 72392e84a097
Revises: 353d8ef550d2
Create Date: 2026-07-28 23:02:54.163974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72392e84a097'
down_revision: Union[str, Sequence[str], None] = '353d8ef550d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user_cv', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.execute("UPDATE user_cv SET is_published = FALSE")
    op.alter_column('user_cv', 'is_published', nullable=False)
    op.add_column('user_cv', sa.Column('public_slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_cv', ['public_slug'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_cv', type_='unique')
    op.drop_column('user_cv', 'public_slug')
    op.drop_column('user_cv', 'is_published')
    # ### end Alembic commands ###
